import Head from 'next/head';
import Image from 'next/image';

export default function Home() {
  return (
    <>
      <Head>
        <title>Wassim Serhan Photography</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="street photography" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ display: 'block', padding: '2rem 0' }}>
        <Image layout="fixed" width="800" height="600" src="/images/hero.jpg" />
      </div>
    </>
  );
}
